# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
  node-executor:
    docker:
      -image: circleci/node/


jobs:
    build:
        docker:
            - image: circleci/node:7.10

        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
                    - run: npm install

            - save_cache:
                paths:
                    - node_modules
                    key: v1-dependencies-{{ checksum "package.json" }}
                    - run: npm test


    lint:

    executor: node-executor
    working_directory: ~/webapp
    steps:
        - checkout
        - attatch_workspace:
            at: ~/webapp
            - run: npm run lint

    test:
        executor: node-executor
        working_directory: ~/webapp
        steps:
            - checkout
            - attatch_workspace:
                at: ~/webapp
                - run: npm test

workflows:
    version: 2
    github_pipeline:
        jobs:
            - install-dependencies
                filters:
                ignore: gh-pages   #how to ignore a branch. If we push a change in this area, circleCI won't run.
            - lint:
                requires:
                    - install-Dependencies
            - test:
                requires:
                    - install-dependencies



